version: '3.0'

services:

  mongo:
    container_name: mongo-alura
    image: mongo
    volumes:
      - db-mongo-alura:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  db-mongo-alura:
